name: Openeuler gitee large repos mirror periodic job test

on:
  pull_request:
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
    paths:
    - '.github/workflows/**'
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache openEuler src repos
      uses: actions/cache@v2
      with:
        path: /home/runner/work/openeuler-mirror/sync-config/large-sync-cache
        key: ${{ runner.os }}-large-sync-cache
    - name: Mirror the gitee/openeuler org repos to github/openeuler-mirror.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: gitee/openeuler
        dst: github/openeuler-mirror
        dst_key: ${{ secrets.SYNC_EULER_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_EULER_TOKEN }}
        account_type: org
        clone_style: ssh
        force_update: true
        debug: true
        timeout: '1h' 
        static_list: "kernel,qemu,raspberrypi,raspberrypi-kernel,website-v2"
        cache_path: /github/workspace/large-sync-cache
