name: Gitee repos mirror periodic job

on:
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.03
      with:
        src: gitee/openeuler
        dst: github/openeuler-mirror
        dst_key: ${{ secrets.SYNC_EULER_PRIVATE_KEY }}
        dst_token:  ${{ secrets.SYNC_EULER_TOKEN }}
        account_type: org
